### ISSUE TITLE
Fails to build on rustc 1.0.0-nightly (522d09dfe 2015-02-19)

### ISSUE THREAD

**Issue by bfops** [netvl/xml-rs#72]
Compiling xml-rs v0.1.18 (file:///home/ben/xml-rs)
    src/util.rs:1:5: 1:28 error: unresolved import `std::borrow::BorrowFrom`. There is no `BorrowFrom` in `std::borrow`
    src/util.rs:1 use std::borrow::BorrowFrom;
                      ^~~~~~~~~~~~~~~~~~~~~~~
    error: aborting due to previous error
    Could not compile `xml-rs`.

    To learn more, run the command again with --verbose.

**Comment by bfops** [comment]
I'm working on a PR right now.
